added configurable port
djenriquez/zookeeper-exhibitor pull request #1
Opened 2017-06-08 01:40 UTC by simplesteph

2017-06-14 23:45 UTC, djenriquez requested changes
@simplesteph Could you please update this so it follows the pattern for the other vars?

On line 24:
```
 : ${EXHIBITOR_PORT:=8181}
```
Then on line 94:
```
--port ${EXHIBITOR_PORT} --defaultconfig /opt/exhibitor/defaults.conf \
```

Thanks and sorry for the delayed response, totally forgot about this PR when I saw it on my email.

2017-06-14 23:56 UTC, simplesteph commented
@djenriquez done.

2017-06-15 06:33 UTC, djenriquez commented
Thanks @simplesteph

2017-06-15 06:34 UTC, djenriquez approved these changes

2017-06-15 06:34 UTC, merged